repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude: |
          (?x)^(
            frontend/public/orb.png |
            frontend/package-lock.json
          )$
  - repo: local
    hooks:
      # Hooks for the token dispenser
      - id: cargo-fmt-token-dispenser
        name: Cargo format for token dispenser
        language: "rust"
        entry: cargo +nightly-2023-07-23 fmt --manifest-path ./token-dispenser/Cargo.toml --all -- --config-path ./token-dispenser/rustfmt.toml
        pass_filenames: false
        files: token-dispenser
      - id: cargo-clippy-token-dispenser
        name: Cargo clippy for token dispenser
        language: "rust"
        entry: cargo +nightly-2023-07-23 clippy --manifest-path ./token-dispenser/Cargo.toml --tests --fix --allow-dirty --allow-staged -- -D warnings
        pass_filenames: false
        files: token-dispenser
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@2.7.1"
          - "prettier-plugin-tailwindcss@^0.1.13"
