[features]
seeds = false
skip-lint = false
[programs.localnet]
token_dispenser = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf"
export = "anchor build && ./scripts/export_idl.sh"
