[package]
name = "token-dispenser"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_dispenser"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.27.0", features = ["init-if-needed"] }
pythnet-sdk = { git = "https://github.com/pyth-network/pyth-crosschain.git"}


[dev-dependencies]
solana-program-test = "1.14.16"
solana-sdk = "1.14.16"
bincode = "1.3.3"
libsecp256k1= "0.6.0"
hex = "0.4.3"
ed25519-consensus = "2.1.0"
ed25519-dalek = "1.0.1"
bytemuck = "1.13.1"
