name: Frontend Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.27.0

    env:
      PGUSER: myuser
      PGPASSWORD: mypass
      PGDATABASE: mydb

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: ${{ env.PGDATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    #      solana:
    #        image: projectserum/build:v0.27.0

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Set default toolchain
        run: rustup default stable
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Generate new keygen
        run: solana-keygen new
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get
      #      - name: Install yarn dependencies
      #        run: yarn install
      #      - uses: actions-rs/toolchain@v1
      #        with:
      #          profile: minimal
      #          toolchain: nightly-2023-03-01
      #          components: rustfmt, clippy
      #      - name: Install Solana
      #        run: |
      #          sh -c "$(curl -sSfL https://release.solana.com/v1.14.20/install)"
      #          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      #      - name: Generate Solana Key
      #        run: solana-keygen new --no-bip39-passphrase
      #        shell: bash
      #      - name: Install Anchor
      #        run: |
      #          cargo install --git https://github.com/coral-xyz/anchor --tag v0.27.0 anchor-cli --locked
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Test
        run: npm run setup-test-ci
      #      - name: Migrate DB
      #        run: npm run migrate
      - name: Test
        run: npm run test
